"""initial schema

Revision ID: 299e617f254d
Revises:
Create Date: 2026-08-30 18:54:07.586167

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "299e617f254d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "papers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pmid", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("authors", sa.Text(), nullable=True),
        sa.Column("journal", sa.String(length=300), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("doi", sa.String(length=200), nullable=True),
        sa.Column("url", sa.String(length=400), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_papers_pmid", "papers", ["pmid"], unique=True)
    op.create_index("ix_papers_publication_date", "papers", ["publication_date"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("research_question", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence_extractions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("population", sa.Text(), nullable=True),
        sa.Column("intervention", sa.Text(), nullable=True),
        sa.Column("comparison", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("study_design", sa.String(length=150), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("key_finding", sa.Text(), nullable=True),
        sa.Column("limitations", sa.Text(), nullable=True),
        sa.Column("confidence", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IN ('low', 'medium', 'high')", name="ck_evidence_extractions_confidence"
        ),
        sa.CheckConstraint(
            "sample_size IS NULL OR sample_size >= 0", name="ck_evidence_extractions_sample_size"
        ),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_extractions_paper_id"), "evidence_extractions", ["paper_id"], unique=False
    )
    op.create_table(
        "review_papers",
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'screened', 'included', 'excluded')",
            name="ck_review_papers_status",
        ),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("review_id", "paper_id"),
    )
    op.create_index("ix_review_papers_paper_id", "review_papers", ["paper_id"], unique=False)
    op.create_index("ix_review_papers_review_id", "review_papers", ["review_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_papers_review_id", table_name="review_papers")
    op.drop_index("ix_review_papers_paper_id", table_name="review_papers")
    op.drop_table("review_papers")
    op.drop_index(op.f("ix_evidence_extractions_paper_id"), table_name="evidence_extractions")
    op.drop_table("evidence_extractions")
    op.drop_table("reviews")
    op.drop_index("ix_papers_publication_date", table_name="papers")
    op.drop_index("ix_papers_pmid", table_name="papers")
    op.drop_table("papers")
    # ### end Alembic commands ###
